In [1]:
import h5py
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten, GlobalAveragePooling2D, Dropout, MaxPooling2D

In [3]:
f_train = h5py.File("sample_A_padded_20160501.hdf")
pixels = f_train['volumes']['raw']
labels = f_train['volumes']['labels']['neuron_ids']

# convert training data
train_data = np.array(pixels[::].tolist())
train_labels = np.array(labels[::].tolist())
print(train_data)

[[[ 94  99 107 ... 110 111 108]
  [ 96  97 104 ... 124 117 109]
  [ 92  95  99 ... 138 128 119]
  ...
  [106 110 119 ... 166 164 165]
  [ 93  89 102 ... 174 169 167]
  [ 80  81  86 ... 173 171 167]]

 [[ 75  86  88 ... 132 133 136]
  [ 81  87  88 ... 123 123 127]
  [ 82  93  89 ... 110 119 123]
  ...
  [ 84  92  83 ... 154 154 155]
  [ 83  87  88 ... 158 158 160]
  [ 83  91  94 ... 165 164 164]]

 [[132 126 132 ... 132 130 125]
  [132 129 120 ... 119 115 115]
  [131 124 120 ... 108 109 111]
  ...
  [125 122 117 ... 158 162 162]
  [121 118 112 ... 163 163 157]
  [120 113 113 ... 163 166 158]]

 ...

 [[154 157 159 ... 154 155 160]
  [159 156 158 ... 157 161 163]
  [149 154 163 ... 160 162 164]
  ...
  [ 75  78  88 ... 123 124 118]
  [ 75  77  85 ... 139 138 133]
  [ 78  76  80 ... 146 146 143]]

 [[153 152 151 ... 161 163 161]
  [153 148 144 ... 159 159 160]
  [149 145 141 ... 153 152 154]
  ...
  [ 95  93  91 ...  87  86  97]
  [101  97  94 ...  85  89  88]
  [111 107  98 ...  81  91  

In [4]:
import tensorflow as tf

train_set, val_set = tf.keras.utils.split_dataset(train_data, left_size=0.8)
train_label, val_label = tf.keras.utils.split_dataset(train_labels, left_size=0.8)

InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized.

In [ ]:
model = Sequential()

model.add(Dense(250, activation='softmax',
                input_shape=(1250, 1250)))
model.add(Dropout(0.5))
model.add(Dense(1250, activation='softmax'))

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(train_data,
          train_labels,
          batch_size=10,
          shuffle=True,
          epochs=3)